
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 14 17:17:24 SGT 2014
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CONS = 10;
  public static final int FUNCTION = 7;
  public static final int UMINUS = 23;
  public static final int LPAREN = 17;
  public static final int GREATER = 25;
  public static final int LESS = 24;
  public static final int MINUS = 20;
  public static final int RPAREN = 18;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int APPEND = 9;
  public static final int TAIL = 12;
  public static final int IN = 3;
  public static final int OR = 29;
  public static final int COMMA = 16;
  public static final int EQUALEQUAL = 33;
  public static final int EMPTYLIST = 13;
  public static final int DIV = 22;
  public static final int GEQ = 27;
  public static final int PLUS = 19;
  public static final int IF = 4;
  public static final int LSQBR = 14;
  public static final int EOF = 0;
  public static final int EQUAL = 34;
  public static final int TRUE = 31;
  public static final int error = 1;
  public static final int NUMBER = 36;
  public static final int HEAD = 11;
  public static final int TIMES = 21;
  public static final int ARROW = 8;
  public static final int ELSE = 6;
  public static final int LET = 2;
  public static final int THEN = 5;
  public static final int LEQ = 26;
  public static final int RSQBR = 15;
  public static final int STRING = 37;
  public static final int FALSE = 32;
  public static final int IDENTIFIER = 35;
}

